# Generated by Django 5.0.6 on 2026-04-09 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time')], default='full_time', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('hired', 'Hired'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='open', max_length=15)),
                ('work_location', models.CharField(max_length=255)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('requirements', models.TextField(blank=True, help_text='Job requirements or special instructions for the driver.')),
                ('agreed_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Agreed hourly or daily rate.', max_digits=8, null=True)),
                ('total_earned', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount earned by the driver for this engagement.', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hired_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('client_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('driver_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs_as_client', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_as_driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('hired', 'Hired'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='jobs.jobengagement')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
