# Generated by Django 5.0.6 on 2026-04-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_driver_status_no_offline'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='licenses/'),
        ),
    ]
