# Generated by Django 5.0.6 on 2026-04-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='twilio_sid',
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
